### PR TITLE
Upgrade to controller-runtime 0.9.2 and operator-sdk 1.6.1.

### PR DESCRIPTION
**Pull request by Miles-Garnsey**
We need features from the 0.8.3 controller runtime version to test changes in PR #70. 

This PR upgrades various pieces to make this fly.

### CODE REVIEW

**Comment by Miles-Garnsey** [comment]
Converting to draft. e2e tests failing somewhere, not detected by `make test` but it pops up in the GH actions.

**Comment by jsanda** [comment]
Why bother with upgrading? We are going to be migrating the controllers and CRD(s) init k8ssandra-operator soon.

**Comment by Miles-Garnsey** [comment]
We can't finish reaper-operator #70 without upgrading. It doesn't do me any harm to get to know a bit more about how the controller-runtime, operator-sdk and kubebuilder fit together too.

**Comment by jdonenine** [comment]
@Miles-Garnsey will what you've started here address the issues with the removed APIs in v1.22 from #76 ?

**Review by jsanda — APPROVED** [review]
@miles the changes look good. Please create a follow up ticket/PR to test and incorporate the changes into k8ssandra.

**Pull request merged**
